// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5mIxZBlZ49B_FMbSayujqE0f17GX8RNM',
    appId: '1:425464192162:web:66bbecdd7d0fc7c11ecbfb',
    messagingSenderId: '425464192162',
    projectId: 'instagram-clone-stg-f9f62',
    authDomain: 'instagram-clone-stg-f9f62.firebaseapp.com',
    storageBucket: 'instagram-clone-stg-f9f62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVQWFRqRws-q-2uo_4QhpRIx1jkWdzSk',
    appId: '1:425464192162:android:1a126c03a0a00abe1ecbfb',
    messagingSenderId: '425464192162',
    projectId: 'instagram-clone-stg-f9f62',
    storageBucket: 'instagram-clone-stg-f9f62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPROZsVDE0v2RbRr9_Zzh3FA5_pI1xTO4',
    appId: '1:425464192162:ios:09914b1083cfea051ecbfb',
    messagingSenderId: '425464192162',
    projectId: 'instagram-clone-stg-f9f62',
    storageBucket: 'instagram-clone-stg-f9f62.appspot.com',
    iosClientId: '425464192162-hfpvt62i2pt6qaecs85rk86ti5ts6de2.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPROZsVDE0v2RbRr9_Zzh3FA5_pI1xTO4',
    appId: '1:425464192162:ios:09914b1083cfea051ecbfb',
    messagingSenderId: '425464192162',
    projectId: 'instagram-clone-stg-f9f62',
    storageBucket: 'instagram-clone-stg-f9f62.appspot.com',
    iosClientId: '425464192162-hfpvt62i2pt6qaecs85rk86ti5ts6de2.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5mIxZBlZ49B_FMbSayujqE0f17GX8RNM',
    appId: '1:425464192162:web:9454e840c54745681ecbfb',
    messagingSenderId: '425464192162',
    projectId: 'instagram-clone-stg-f9f62',
    authDomain: 'instagram-clone-stg-f9f62.firebaseapp.com',
    storageBucket: 'instagram-clone-stg-f9f62.appspot.com',
  );
}
