// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xI_vNd52K58SU5e9gO7a1jku0a_XOTk',
    appId: '1:582122810857:web:866d7a505dbc51c45a2f78',
    messagingSenderId: '582122810857',
    projectId: 'instagram-clone-prod-bfb8b',
    authDomain: 'instagram-clone-prod-bfb8b.firebaseapp.com',
    storageBucket: 'instagram-clone-prod-bfb8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSGFM2hPeZoG9NOEqDOAraY-r4w4FQb4',
    appId: '1:582122810857:android:5be74a8bc811a7775a2f78',
    messagingSenderId: '582122810857',
    projectId: 'instagram-clone-prod-bfb8b',
    storageBucket: 'instagram-clone-prod-bfb8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvBlN3ylWOY0u7jUCwdgMf2jtfF0DrTPQ',
    appId: '1:582122810857:ios:2b5c9016df2ac2845a2f78',
    messagingSenderId: '582122810857',
    projectId: 'instagram-clone-prod-bfb8b',
    storageBucket: 'instagram-clone-prod-bfb8b.appspot.com',
    iosClientId: '582122810857-ahb4987qdtcj2gu7pdrc5ab1juj5nq19.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvBlN3ylWOY0u7jUCwdgMf2jtfF0DrTPQ',
    appId: '1:582122810857:ios:2b5c9016df2ac2845a2f78',
    messagingSenderId: '582122810857',
    projectId: 'instagram-clone-prod-bfb8b',
    storageBucket: 'instagram-clone-prod-bfb8b.appspot.com',
    iosClientId: '582122810857-ahb4987qdtcj2gu7pdrc5ab1juj5nq19.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xI_vNd52K58SU5e9gO7a1jku0a_XOTk',
    appId: '1:582122810857:web:e317a37e66de9ad45a2f78',
    messagingSenderId: '582122810857',
    projectId: 'instagram-clone-prod-bfb8b',
    authDomain: 'instagram-clone-prod-bfb8b.firebaseapp.com',
    storageBucket: 'instagram-clone-prod-bfb8b.appspot.com',
  );
}
