// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP9STWtEiGD5gPLzCdbcjNan-9vblMzbo',
    appId: '1:799216528975:web:8deeb2ef1ee979be74843a',
    messagingSenderId: '799216528975',
    projectId: 'instagram-clone-dev-4150c',
    authDomain: 'instagram-clone-dev-4150c.firebaseapp.com',
    storageBucket: 'instagram-clone-dev-4150c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0xLd8BB5D0hRjHm2As5gGPBHkKViN-b4',
    appId: '1:799216528975:android:ddea2742ed8651b474843a',
    messagingSenderId: '799216528975',
    projectId: 'instagram-clone-dev-4150c',
    storageBucket: 'instagram-clone-dev-4150c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuK-O85f1E9SWRm2u1IiZN9Bo1TjCzhsg',
    appId: '1:799216528975:ios:cb0fa9bfc352656174843a',
    messagingSenderId: '799216528975',
    projectId: 'instagram-clone-dev-4150c',
    storageBucket: 'instagram-clone-dev-4150c.appspot.com',
    iosClientId: '799216528975-cm3cagg2ml83fv8stsdo4ods3q80l0p9.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuK-O85f1E9SWRm2u1IiZN9Bo1TjCzhsg',
    appId: '1:799216528975:ios:cb0fa9bfc352656174843a',
    messagingSenderId: '799216528975',
    projectId: 'instagram-clone-dev-4150c',
    storageBucket: 'instagram-clone-dev-4150c.appspot.com',
    iosClientId: '799216528975-cm3cagg2ml83fv8stsdo4ods3q80l0p9.apps.googleusercontent.com',
    iosBundleId: 'com.chamuditha.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP9STWtEiGD5gPLzCdbcjNan-9vblMzbo',
    appId: '1:799216528975:web:cd81f32161d2643074843a',
    messagingSenderId: '799216528975',
    projectId: 'instagram-clone-dev-4150c',
    authDomain: 'instagram-clone-dev-4150c.firebaseapp.com',
    storageBucket: 'instagram-clone-dev-4150c.appspot.com',
  );
}
